language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
services:
  - mysql
before_script:
  - composer update
  - composer install
  - mv tests/test_env .env
  - mysql -e 'CREATE DATABASE polrci;'
  - php artisan migrate --force
  - composer install
notifications:
  email: false
