language: php
php:
  - '5.6'
  - '7.0'
  - '7.2'
  - '7.3'
services:
  - mysql
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - composer install
  - mv tests/test_env .env
  - mysql -e 'CREATE DATABASE polrci;'
  - php artisan migrate --force
  - composer install
notifications:
  email: false
